project_id = "jvlpjqwwxzlceircfpis"

[functions.submit-inquiry]
verify_jwt = false

[functions.lookup-inquiry]
verify_jwt = false

[functions.send-reply-email]
verify_jwt = false

[functions.manage-user-role]
verify_jwt = false
